name: Market Daily Email (USA)

on:
  schedule:
    - cron: '0 13 * * *'  # 06:00 PDT (UTC-7)
    - cron: '0 14 * * *'  # 06:00 PST (UTC-8)
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Compute Pacific hour
        id: timecheck
        run: |
          echo "hour=$(TZ=America/Los_Angeles date +%H)" >> "$GITHUB_OUTPUT"
          echo "Pacific hour: $(TZ=America/Los_Angeles date +%H)"

      - name: Install dependencies
        if: ${{ github.event_name != 'schedule' || steps.timecheck.outputs.hour == '06' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write .env from secret
        if: ${{ github.event_name != 'schedule' || steps.timecheck.outputs.hour == '06' }}
        env:
          DAILY_TLDR_ENV: ${{ secrets.DAILY_TLDR_ENV }}
        run: |
          printf '%s' "$DAILY_TLDR_ENV" > .env
          chmod 600 .env

      - name: Set USA subject prefix and focus
        if: ${{ github.event_name != 'schedule' || steps.timecheck.outputs.hour == '06' }}
        run: |
          # Ensure newline at end of file before appending
          tail -c1 .env | read -r _ || echo >> .env
          # Normalize subject prefix to short USA form
          sed -i '""' -e '/^SUBJECT_PREFIX=/d' .env || true
          echo 'SUBJECT_PREFIX=Market Daily TL;DR USA' >> .env
          # Append focus market on its own line
          echo 'FOCUS_MARKET=United States (S&P 500, Fed, CPI/PPI, USD, UST rates, major US corporates)' >> .env

      - name: Send daily email
        if: ${{ github.event_name != 'schedule' || steps.timecheck.outputs.hour == '06' }}
        run: |
          python daily_emailer.py 