name: Market Daily Email

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 06:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write .env from secret
        env:
          DAILY_TLDR_ENV: ${{ secrets.DAILY_TLDR_ENV }}
        run: |
          printf '%s' "$DAILY_TLDR_ENV" > .env
          chmod 600 .env

      - name: Send daily email
        run: |
          python daily_emailer.py 